apiVersion: v1
kind: Namespace
metadata:
  name: kubeseal
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
spec:
  project: default
  source:
    chart: sealed-secrets
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 1.2.8
    helm:
      releaseName: sealed-secrets
      # valueFiles:
      # - values-production.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kubeseal